### PR TITLE
clustermembercontroller: fix incorrect error reporting during bootstrap

### LINKED ISSUE #47: operator not reporting accurate status
#39 added support to report conditions in Etcd Status.

When etcd-operator pod is deployed, it sees etcd-bootstrap host. Before other members are observed, it reports the operator is available: true, progressing: false and degraded: false.

```
I1216 16:44:59.968237       1 clustermembercontroller.go:614] observed members: []interface {}{map[string]interface {}{"name":"etcd-bootstrap", "peerURLs":"https://10.0.2.26:2380", "status":"Unknown"}}
I1216 16:44:59.976202       1 statuscontroller.go:175] clusteroperator/openshift-etcd diff {"status":{"conditions":[{"lastTransitionTime":"2019-12-16T16:43:29Z","message":"ConfigObservationDegraded: error looking up self: lookup _etcd-server-ssl._tcp.alpa
tel-ceo441.devcluster.openshift.com on 172.30.0.10:53: read udp 10.130.0.12:44974-\u003e172.30.0.10:53: i/o timeout\nConfigObservationDegraded: non-deterministic config observation detected","reason":"ConfigObservationDegradedError","status":"True","type"
:"Degraded"},{"lastTransitionTime":"2019-12-16T16:44:59Z","reason":"AsExpected","status":"False","type":"Progressing"},{"lastTransitionTime":"2019-12-16T16:44:59Z","reason":"AsExpected","status":"True","type":"Available"},{"lastTransitionTime":"2019-12-16
T16:44:59Z","reason":"AsExpected","status":"True","type":"Upgradeable"}]}}
I1216 16:44:59.976699       1 waitforceo.go:70] Cluster etcd operator bootstrapped successfully
I1216 16:44:59.976796       1 waitforceo.go:58] cluster-etcd-operator bootstrap etcd
I1216 16:44:59.976956       1 clustermembercontroller.go:276] All cluster members observed, scaling complete!
``` 
The teardown.go sees this and tries to remove etcd-bootstrap and fails dragging Etcd to a degraded state.

Long term we need to be able to bring the number of master nodes from installer according to the discussion [here](https://github.com/openshift/cluster-etcd-operator/pull/39#pullrequestreview-327725219).

### PR DESCRIPTION
**Pull request by alaypatel07**
fixes #47

### CODE REVIEW

File: pkg/operator/clustermembercontroller/clustermembercontroller_test.go [hunk 1]
```diff
@@ -17,6 +16,15 @@ import (
 	"k8s.io/client-go/kubernetes"
 	"k8s.io/client-go/kubernetes/fake"
 	"k8s.io/client-go/util/workqueue"
+	"k8s.io/klog"
+)
+
+var (
+	//Todo: refactor this by making a function for getting observedConfig
```
Comment (alaypatel07) [inline pkg/operator/clustermembercontroller/clustermembercontroller_test.go]: need to remove this

File: pkg/operator/clustermembercontroller/clustermembercontroller.go [hunk 2]
```diff
@@ -594,33 +588,28 @@ func (c *ClusterMemberController) getResyncName(pods *corev1.PodList) (string, e
...
+		klog.Errorf("error getting members: %#v", err)
 		return false
 	}
-	if len(pendingMembers) > 0 {
-		klog.Infof("some members are pending: %#v", pendingMembers)
+	if len(members) == 0 {
+		klog.Infof("no etcd member found")
+		return false
+	}
+	if len(members) < 2 && c.IsMember("etcd-bootstrap") {
```
Comment (retroflexer) [inline pkg/operator/clustermembercontroller/clustermembercontroller.go]: Minor thing, but why `< 2`? Isn't `==1` is more readable? (we are already checking for `==0` above, so the only value we want to see is `1`, since length can never be negative).

**Comment by retroflexer** [comment]
/lgtm

Code looks reasonable. Since this is going into 4.4, we will take care of any issues coming out from it.

File: pkg/operator/clustermembercontroller/clustermembercontroller.go (hunk 2 above)
Comment (alaypatel07) [reply pkg/operator/clustermembercontroller/clustermembercontroller.go]: yes, it is, I will update it!

Comment (alaypatel07) [reply pkg/operator/clustermembercontroller/clustermembercontroller.go]: updated

File: pkg/operator/clustermembercontroller/clustermembercontroller_test.go (hunk 1 above)
Comment (alaypatel07) [reply pkg/operator/clustermembercontroller/clustermembercontroller_test.go]: removed
